#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LottoCalc.Resource", IsApplication=true)]

namespace LottoCalc
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int ButtonClear = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int ButtonCompute = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int MenuitemOptionsAbout = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int MenuitemOptionsSettings = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int SpinnerGame = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int TextviewResult = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int Options = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int AboutMessage = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AboutTitle = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int AboutVersion = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ApplicationName = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int ButtonTextClear = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int ButtonTextCompute = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int ButtonTextOK = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int LabelSettings = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int PromptSelectGame = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int ToastResultCleared = 2131034121;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
